//AUTH

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
//AUTH

//Users
export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const FETCH_USER_LIST_SUCCESS = "FETCH_USER_LIST_SUCCESS";
export const FETCH_USER_LIST_FAIL = "FETCH_USER_LIST_FAIL";

export const EDIT_USER_DETAIL_MODAL = "EDIT_USER_DETAIL_MODAL ";

export const SAVE_USERS_DETAILS = "SAVE_USERS_DETAILS";
export const SAVE_USERS_DETAILS_SUCCESS = "SAVE_USERS_DETAILS_SUCCESS";
export const SAVE_USERS_DETAILS_FAIL = "SAVE_USERS_DETAILS_FAIL";

export const ALERT_MODALS_SHOW_USERS = "ALERT_MODALS_SHOW_USERS";

//Users
