//AUTH

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
//AUTH

//Users
export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const FETCH_USER_LIST_SUCCESS = "FETCH_USER_LIST_SUCCESS";
export const FETCH_USER_LIST_FAIL = "FETCH_USER_LIST_FAIL";

export const EDIT_USER_DETAIL_MODAL = "EDIT_USER_DETAIL_MODAL ";

export const SAVE_USERS_DETAILS = "SAVE_USERS_DETAILS";
export const SAVE_USERS_DETAILS_SUCCESS = "SAVE_USERS_DETAILS_SUCCESS";
export const SAVE_USERS_DETAILS_FAIL = "SAVE_USERS_DETAILS_FAIL";

export const UPDATE_USERS_DETAILS = "UPDATE_USERS_DETAILS";
export const UPDATE_USERS_DETAILS_SUCCESS = "UPDATE_USERS_DETAILS_SUCCESS";
export const UPDATE_USERS_DETAILS_FAIL = "UPDATE_USERS_DETAILS_FAIL";

export const DELETE_USERS_DETAILS = "DELETE_USERS_DETAILS";
export const DELETE_USERS_DETAILS_SUCCESS = "DELETE_USERS_DETAILS_SUCCESS";
export const DELETE_USERS_DETAILS_FAIL = "DELETE_USERS_DETAILS_FAIL";

export const ALERT_MODALS_SHOW_USERS = "ALERT_MODALS_SHOW_USERS";

//Users

//shipping agent

export const FETCH_SHIPPING_AGENT_LIST = "FETCH_SHIPPING_AGENT_LIST";
export const FETCH_SHIPPING_AGENT_LIST_SUCCESS =
  "FETCH_SHIPPING_AGENT_LIST_SUCCESS";
export const FETCH_SHIPPING_AGENT_LIST_FAIL = "FETCH_SHIPPING_AGENT_LIST_FAIL";

export const EDIT_SHIPPING_AGENT_DETAIL_MODAL =
  "EDIT_SHIPPING_AGENT_DETAIL_MODAL ";

export const SAVE_SHIPPING_AGENTS_DETAILS = "SAVE_SHIPPING_AGENTS_DETAILS";
export const SAVE_SHIPPING_AGENTS_DETAILS_SUCCESS =
  "SAVE_SHIPPING_AGENTS_DETAILS_SUCCESS";
export const SAVE_SHIPPING_AGENTS_DETAILS_FAIL =
  "SAVE_SHIPPING_AGENTS_DETAILS_FAIL";

export const UPDATE_SHIPPING_AGENTS_DETAILS = "UPDATE_SHIPPING_AGENTS_DETAILS";
export const UPDATE_SHIPPING_AGENTS_DETAILS_SUCCESS =
  "UPDATE_SHIPPING_AGENTS_DETAILS_SUCCESS";
export const UPDATE_SHIPPING_AGENTS_DETAILS_FAIL =
  "UPDATE_SHIPPING_AGENTS_DETAILS_FAIL";

export const DELETE_SHIPPING_AGENTS_DETAILS = "DELETE_SHIPPING_AGENTS_DETAILS";
export const DELETE_SHIPPING_AGENTS_DETAILS_SUCCESS =
  "DELETE_SHIPPING_AGENTS_DETAILS_SUCCESS";
export const DELETE_SHIPPING_AGENTS_DETAILS_FAIL =
  "DELETE_SHIPPING_AGENTS_DETAILS_FAIL";

export const ALERT_MODALS_SHOW_SHIPPING_AGENTS =
  "ALERT_MODALS_SHOW_SHIPPING_AGENTS";
//shipping agent

//shipping agent

export const FETCH_VESSEL_LIST = "FETCH_VESSEL_LIST";
export const FETCH_VESSEL_LIST_SUCCESS = "FETCH_VESSEL_LIST_SUCCESS";
export const FETCH_VESSEL_LIST_FAIL = "FETCH_VESSEL_LIST_FAIL";

export const EDIT_VESSEL_DETAIL_MODAL = "EDIT_VESSEL_DETAIL_MODAL ";

export const SAVE_VESSELS_DETAILS = "SAVE_VESSELS_DETAILS";
export const SAVE_VESSELS_DETAILS_SUCCESS = "SAVE_VESSELS_DETAILS_SUCCESS";
export const SAVE_VESSELS_DETAILS_FAIL = "SAVE_VESSELS_DETAILS_FAIL";

export const UPDATE_VESSELS_DETAILS = "UPDATE_VESSELS_DETAILS";
export const UPDATE_VESSELS_DETAILS_SUCCESS = "UPDATE_VESSELS_DETAILS_SUCCESS";
export const UPDATE_VESSELS_DETAILS_FAIL = "UPDATE_VESSELS_DETAILS_FAIL";

export const DELETE_VESSELS_DETAILS = "DELETE_VESSELS_DETAILS";
export const DELETE_VESSELS_DETAILS_SUCCESS = "DELETE_VESSELS_DETAILS_SUCCESS";
export const DELETE_VESSELS_DETAILS_FAIL = "DELETE_VESSELS_DETAILS_FAIL";

export const ALERT_MODALS_SHOW_VESSELS = "ALERT_MODALS_SHOW_VESSELS";
//shipping agent

//crew

export const FETCH_CREW_LIST = "FETCH_CREW_LIST";
export const FETCH_CREW_LIST_SUCCESS = "FETCH_CREW_LIST_SUCCESS";
export const FETCH_CREW_LIST_FAIL = "FETCH_CREW_LIST_FAIL";

//crew

//Arrival
export const FETCH_ARRIVAL_LIST = "FETCH_ARRIVAL_LIST";
export const FETCH_ARRIVAL_LIST_SUCCESS = "FETCH_ARRIVAL_LIST_SUCCESS";
export const FETCH_ARRIVAL_LIST_FAIL = "FETCH_ARRIVAL_LIST_FAIL";

export const SAVE_ARRIVAL_DETAILS = "SAVE_ARRIVAL_DETAILS";
export const SAVE_ARRIVAL_DETAILS_SUCCESS = "SAVE_ARRIVAL_DETAILS_SUCCESS";
export const SAVE_ARRIVAL_DETAILS_FAIL = "SAVE_ARRIVAL_DETAILS_FAIL";

export const EDIT_ARRIVAL_DETAIL_MODAL = "EDIT_ARRIVAL_DETAIL_MODAL ";
//Arrival
